### ISSUE TITLE
非常感兴趣这个项目，有交流群吗？

### ISSUE THREAD

**Issue by weicheng59** [huchenxucs/ChatDB#3]
感谢开发者开源出来为社区做出的贡献，希望有一个方式可以和开发者交流使用体验和具体细节。

**Comment by tianranhunda** [comment]
![Weixin Image_20230628115021](https://github.com/huchenxucs/ChatDB/assets/104623026/10853d34-d6e1-489f-a239-677301c55b20)
我建了一个微信群，希望感兴趣这个项目的朋友一起参与讨论。

**Comment by khill-fbmc** [comment]
ChatGPT translation for the English speakers:
> "I have created a WeChat group and hope that friends who are interested in this project can join the discussion."

**Comment by potong** [comment]
> ![Weixin Image_20230628115021](https://user-images.githubusercontent.com/104623026/249341331-10853d34-d6e1-489f-a239-677301c55b20.jpg) 我建了一个微信群，希望感兴趣这个项目的朋友一起参与讨论。

能更新下微信群吗

**Comment by xxzcool** [comment]
能更新下微信群吗

**Comment by xxzcool** [comment]
> ![Weixin Image_20230628115021](https://user-images.githubusercontent.com/104623026/249341331-10853d34-d6e1-489f-a239-677301c55b20.jpg) 我建了一个微信群，希望感兴趣这个项目的朋友一起参与讨论。

过期了，能重发一下微信群吗，感谢~

**Comment by Erakee** [comment]
您好，能再发一下交流群吗？谢谢
